### ISSUE TITLE
Peer to peer code review 

### ISSUE THREAD

**Issue by ErikStoupignan** [Aseadd/Leaderboard#4]
# Peer to peer code review
## Hello @Aseadd, good morning!
You did an excellent job with your repository. Your code looks very clean and tidy.

![goodJob](https://media.giphy.com/media/duNowzaVje6Di3hnOu/giphy-downsized-large.gif)

- We saw that you created your entire DOM from the JavaScript file and did great. We think that when the code is so small, you could do it directly in the HTML file to avoid confusion.
- The add function is defined as "async" but is not necessary because the data it is reading comes from the inputs so it does not have to wait.
- The "refresh" function was not defined but was a very brief configuration.

We were glad that your program will be working so well. Excellent work!

**Comment by Aseadd** [comment]
Thank you my friend for the comments, I have addressed all the comments with big thanks!!!
